framework:
    workflows:
        greeting_publishing:
            type: 'state_machine'
            audit_trail:
                enabled: true
            marking_store:
                type: 'method'
                property: 'status'
            supports:
                - App\Business\Contexts\Greeting\Domain\Greeting
            initial_marking: draft
            places:
                - draft
                - published
                - archived
            transitions:
                publish:
                    from: draft
                    to:   published
                archive:
                    from: published
                    to:   archived
