name: Continuous Integration
on: [push, pull_request]

jobs:
    tests:
        name: Tests Symfony (PHP ${{ matrix.php-versions }} on ${{ matrix.operating-system }})
        runs-on: ${{ matrix.operating-system }}
        strategy:
            fail-fast: false
            matrix:
                operating-system: [ubuntu-latest]
                php-versions: ['8.4']

        steps:
            - name: "Checkout code"
              uses: actions/checkout@v5
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3
            - name: Build Docker images
              uses: docker/bake-action@v6
              with:
                pull: true
                load: true
                files: |
                    compose.yaml
                    compose.override.yaml
            - name: Start services
              run: docker compose up --wait --no-build
            - name: Check HTTP reachability
              run: curl -v --fail-with-body http://localhost
            - name: Create test database
              run: docker compose exec -T php bin/console -e test doctrine:database:create
            - name: Run migrations
              run: docker compose exec -T php bin/console -e test doctrine:migrations:migrate --no-interaction
            - name: Run PHPUnit
              run: docker compose exec -T php vendor/bin/phpunit
            - name: Doctrine Schema Validator
              run: docker compose exec -T php bin/console -e test doctrine:schema:validate
