framework:
    asset_mapper:
        # The paths to make available to the asset mapper.
        paths:
            - assets/
        excluded_patterns:
            - '*/assets/react/build**'     # React build dir
            - '*/assets/react/src**'       # React sources
        missing_import_mode: strict

react:
    controllers_path: '%kernel.project_dir%/assets/react/dist/controllers'

when@prod:
    framework:
        asset_mapper:
            missing_import_mode: warn
