workers:
    # https://symfony.com/doc/current/setup/symfony_server.html#docker-integration
    docker_compose: ~
    tailwind:
        cmd: ['symfony', 'console', 'tailwind:build', '--watch']
http:
    use_gzip: true
