# Development environment override
services:
  php:
    env_file:
      - path: ./.env.local
        required: false
    build:
      context: .
      target: frankenphp_dev
    volumes:
      - ./:/app
      - /app/var
      - ./frankenphp/Caddyfile:/etc/frankenphp/Caddyfile:ro
      - ./frankenphp/conf.d/20-app.dev.ini:/usr/local/etc/php/app.conf.d/20-app.dev.ini:ro
      # If you develop on Mac or Windows you can remove the vendor/ directory
      #  from the bind-mount for better performance by enabling the next line:
      #- /app/vendor
    environment:
      FRANKENPHP_WORKER_CONFIG: watch
      MERCURE_EXTRA_DIRECTIVES: demo
      APP_ENV: "${APP_ENV:-dev}"
    extra_hosts:
      # Ensure that host.docker.internal is correctly defined on Linux
      - host.docker.internal:host-gateway
    tty: true

  # php-worker:
  #   image: ${IMAGES_PREFIX:-}app-php
  #   build:
  #     context: .
  #     target: frankenphp_dev
  #   restart: unless-stopped
  #   command: php bin/console messenger:consume async -v --limit=10000

###> symfony/mercure-bundle ###
###< symfony/mercure-bundle ###

###> doctrine/doctrine-bundle ###
  database:
    ports:
      - "5432"
###< doctrine/doctrine-bundle ###
