name: App Tests

on: [push, pull_request]

permissions:
    contents: read

jobs:
    tests:
        name: Functional Tests
        runs-on: ubuntu-latest
        steps:
            - 
                name: "Checkout code"
                uses: actions/checkout@v5
            - 
                name: Set up Docker Buildx
                uses: docker/setup-buildx-action@v3
            - 
                name: Build Docker images
                uses: docker/bake-action@v6
                with:
                    pull: true
                    load: true
                    files: |
                        compose.yaml
                        compose.override.yaml
                    set: |
                        *.cache-from=type=gha,scope=${{github.ref}}
                        *.cache-from=type=gha,scope=refs/heads/main
                        *.cache-to=type=gha,scope=${{github.ref}},mode=max
            - 
                name: Start services
                run: docker compose up --detach --no-build
            - 
                name: Check HTTP reachability
                run: curl -v --fail-with-body http://localhost
            - 
                name: Run PHPUnit
                run: docker compose exec -T php bin/phpunit --group=functional --group=integration

    
