name: Unit Tests

on: [push, pull_request]

permissions:
    contents: read

jobs:
    php:
        name: Tests Unitaire (PHP ${{ matrix.php-versions }} on ${{ matrix.operating-system }})
        runs-on: ${{ matrix.operating-system }}
        continue-on-error: false
        strategy:
            matrix:
                operating-system: [ubuntu-latest]
                php-versions: ['8.4']
        steps:
            - 
                name: "Checkout code"
                uses: actions/checkout@v5
            - 
                name: "Install PHP with extensions"
                uses: shivammathur/setup-php@v2
                with:
                    coverage: "none"
                    php-version: ${{ matrix.php-versions }}
                    tools: composer:v2
            - 
                name: "Install dependencies"
                run: composer install --ansi --no-interaction --no-progress
            - 
                name: "Run unit tests"
                run: vendor/bin/phpunit --group=unit

